spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    username: postgres
    password: myP0stgres

  flyway:
    baseline-on-migrate: true

server:
  hostname: localhost
  port: "${PORT:8080}"
mail:
  server:
    host: smtp.gmail.com
    port: 587
    username: iuauusona01@gmail.com
    password: eajy lbkl pklj azrd